### ISSUE TITLE
[FEAT] Logstash "elasticsearch-ingest-pipeline" Optimization

### ISSUE THREAD

**Issue by tankha** [dbeast-co/dbeast-monitor#49]
In case of the many ingest pipelines and many ingest nodes there is huge Logstash CPU usage for the pipeline.
Need to optimize the pipeline for the ingest one document per pipeline

**Comment by dbeast-co** [comment]
TODO:
- [ ] Logstash pipeline optimization
- [ ] "Elasticsearch ingest pipeline" dashboard fix
